from typing import Protocol

from app.domain.entities import EstadoPunto, Incidencia, Paso, PuntoControl


class RepositorioPuntos(Protocol):
    async def listar_archivos(self) -> list[PuntoControl]: ...
    async def ontener(self, punto_id:str) -> PuntoControl | None: ...

class RepositorioPasos(Protocol):
    async def guardar_si_no_existe(self,paso: Paso) -> bool:
        ...

    async def ultimo_paso_de(self,punto_id:str) -> Paso | None: ...

class RepositorioIncidencias(Protocol):
    async def abrir(self, incidencia: Incidencia) -> None: ...
    async def actualizar(self , incidencia: Incidencia) -> None: ...
    async def obtener_abierta(self, puntoid:str) -> list[Incidencia]: ...
    async def listar_abiertas(self) -> list[Incidencia]: ...

class LectorEstadoPuntos(Protocol):
    async def estado_de_todos_los_puntos(self) -> list[EstadoPunto]: ...
