"""tablas iniciales

Revision ID: 0653c8429f2f
Revises: 
Create Date: 2026-08-07 07:36:23.893548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0653c8429f2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitio',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardia',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sitio_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('person_id_externo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sitio_id'], ['sitio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punto_control',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sitio_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nave', sa.String(), nullable=False),
    sa.Column('elemento_id_externo', sa.String(), nullable=False),
    sa.Column('umbral_minutos', sa.Integer(), nullable=False),
    sa.Column('ventana_inicio', sa.Time(), nullable=True),
    sa.Column('ventana_fin', sa.Time(), nullable=True),
    sa.Column('en_mantenimeinto', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sitio_id'], ['sitio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('elemento_id_externo', name='uq_elemento_id_externo')
    )
    op.create_table('incidencia',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('punto_id', sa.String(), nullable=False),
    sa.Column('abierto_en', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(), nullable=True),
    sa.Column('cerrada_por_paso_id', sa.String(), nullable=True),
    sa.Column('ultimo_aviso_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['punto_id'], ['punto_control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paso',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('punto_id', sa.String(), nullable=False),
    sa.Column('guardia_id', sa.String(), nullable=True),
    sa.Column('ocurrido_en', sa.DateTime(), nullable=False),
    sa.Column('evento_id_externo', sa.String(), nullable=False),
    sa.Column('fue_retransmitido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['punto_id'], ['punto_control.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento_id_externo', name='uq_evento_id_externo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paso')
    op.drop_table('incidencia')
    op.drop_table('punto_control')
    op.drop_table('guardia')
    op.drop_table('sitio')
    # ### end Alembic commands ###
